#pragma once

#include <SDL.h>
#include <SDL_scancode.h>
#include <SFML/Window/Keyboard.hpp>

class KeyboardUtil {
public:
    inline static sf::Keyboard::Scancode convertFromSDLToSFML(SDL_Scancode scancode)
    {
        switch (scancode) {
        case SDL_SCANCODE_A:
            return sf::Keyboard::Scancode::A;
        case SDL_SCANCODE_B:
            return sf::Keyboard::Scancode::B;
        case SDL_SCANCODE_C:
            return sf::Keyboard::Scancode::C;
        case SDL_SCANCODE_D:
            return sf::Keyboard::Scancode::D;
        case SDL_SCANCODE_E:
            return sf::Keyboard::Scancode::E;
        case SDL_SCANCODE_F:
            return sf::Keyboard::Scancode::F;
        case SDL_SCANCODE_G:
            return sf::Keyboard::Scancode::G;
        case SDL_SCANCODE_H:
            return sf::Keyboard::Scancode::H;
        case SDL_SCANCODE_I:
            return sf::Keyboard::Scancode::I;
        case SDL_SCANCODE_J:
            return sf::Keyboard::Scancode::J;
        case SDL_SCANCODE_K:
            return sf::Keyboard::Scancode::K;
        case SDL_SCANCODE_L:
            return sf::Keyboard::Scancode::L;
        case SDL_SCANCODE_M:
            return sf::Keyboard::Scancode::M;
        case SDL_SCANCODE_N:
            return sf::Keyboard::Scancode::N;
        case SDL_SCANCODE_O:
            return sf::Keyboard::Scancode::O;
        case SDL_SCANCODE_P:
            return sf::Keyboard::Scancode::P;
        case SDL_SCANCODE_Q:
            return sf::Keyboard::Scancode::Q;
        case SDL_SCANCODE_R:
            return sf::Keyboard::Scancode::R;
        case SDL_SCANCODE_S:
            return sf::Keyboard::Scancode::S;
        case SDL_SCANCODE_T:
            return sf::Keyboard::Scancode::T;
        case SDL_SCANCODE_U:
            return sf::Keyboard::Scancode::U;
        case SDL_SCANCODE_V:
            return sf::Keyboard::Scancode::V;
        case SDL_SCANCODE_W:
            return sf::Keyboard::Scancode::W;
        case SDL_SCANCODE_X:
            return sf::Keyboard::Scancode::X;
        case SDL_SCANCODE_Y:
            return sf::Keyboard::Scancode::Y;
        case SDL_SCANCODE_Z:
            return sf::Keyboard::Scancode::Z;

        case SDL_SCANCODE_1:
            return sf::Keyboard::Scancode::Num1;
        case SDL_SCANCODE_2:
            return sf::Keyboard::Scancode::Num2;
        case SDL_SCANCODE_3:
            return sf::Keyboard::Scancode::Num3;
        case SDL_SCANCODE_4:
            return sf::Keyboard::Scancode::Num4;
        case SDL_SCANCODE_5:
            return sf::Keyboard::Scancode::Num5;
        case SDL_SCANCODE_6:
            return sf::Keyboard::Scancode::Num6;
        case SDL_SCANCODE_7:
            return sf::Keyboard::Scancode::Num7;
        case SDL_SCANCODE_8:
            return sf::Keyboard::Scancode::Num8;
        case SDL_SCANCODE_9:
            return sf::Keyboard::Scancode::Num9;
        case SDL_SCANCODE_0:
            return sf::Keyboard::Scancode::Num0;

        case SDL_SCANCODE_RETURN:
            return sf::Keyboard::Scancode::Enter;
        case SDL_SCANCODE_ESCAPE:
            return sf::Keyboard::Scancode::Escape;
        case SDL_SCANCODE_BACKSPACE:
            return sf::Keyboard::Scancode::Backspace;
        case SDL_SCANCODE_TAB:
            return sf::Keyboard::Scancode::Tab;
        case SDL_SCANCODE_SPACE:
            return sf::Keyboard::Scancode::Space;
        case SDL_SCANCODE_MINUS:
            return sf::Keyboard::Scancode::Hyphen;
        case SDL_SCANCODE_EQUALS:
            return sf::Keyboard::Scancode::Equal;
        case SDL_SCANCODE_LEFTBRACKET:
            return sf::Keyboard::Scancode::LBracket;
        case SDL_SCANCODE_RIGHTBRACKET:
            return sf::Keyboard::Scancode::RBracket;
        case SDL_SCANCODE_BACKSLASH:
            return sf::Keyboard::Scancode::Backslash;
        case SDL_SCANCODE_SEMICOLON:
            return sf::Keyboard::Scancode::Semicolon;
        case SDL_SCANCODE_APOSTROPHE:
            return sf::Keyboard::Scancode::Apostrophe;
        case SDL_SCANCODE_GRAVE:
            return sf::Keyboard::Scancode::Grave;
        case SDL_SCANCODE_COMMA:
            return sf::Keyboard::Scancode::Comma;
        case SDL_SCANCODE_PERIOD:
            return sf::Keyboard::Scancode::Period;
        case SDL_SCANCODE_SLASH:
            return sf::Keyboard::Scancode::Slash;
        case SDL_SCANCODE_CAPSLOCK:
            return sf::Keyboard::Scancode::CapsLock;

        case SDL_SCANCODE_F1:
            return sf::Keyboard::Scancode::F1;
        case SDL_SCANCODE_F2:
            return sf::Keyboard::Scancode::F2;
        case SDL_SCANCODE_F3:
            return sf::Keyboard::Scancode::F3;
        case SDL_SCANCODE_F4:
            return sf::Keyboard::Scancode::F4;
        case SDL_SCANCODE_F5:
            return sf::Keyboard::Scancode::F5;
        case SDL_SCANCODE_F6:
            return sf::Keyboard::Scancode::F6;
        case SDL_SCANCODE_F7:
            return sf::Keyboard::Scancode::F7;
        case SDL_SCANCODE_F8:
            return sf::Keyboard::Scancode::F8;
        case SDL_SCANCODE_F9:
            return sf::Keyboard::Scancode::F9;
        case SDL_SCANCODE_F10:
            return sf::Keyboard::Scancode::F10;
        case SDL_SCANCODE_F11:
            return sf::Keyboard::Scancode::F11;
        case SDL_SCANCODE_F12:
            return sf::Keyboard::Scancode::F12;
        case SDL_SCANCODE_F13:
            return sf::Keyboard::Scancode::F13;
        case SDL_SCANCODE_F14:
            return sf::Keyboard::Scancode::F14;
        case SDL_SCANCODE_F15:
            return sf::Keyboard::Scancode::F15;
        case SDL_SCANCODE_F16:
            return sf::Keyboard::Scancode::F16;
        case SDL_SCANCODE_F17:
            return sf::Keyboard::Scancode::F17;
        case SDL_SCANCODE_F18:
            return sf::Keyboard::Scancode::F18;
        case SDL_SCANCODE_F19:
            return sf::Keyboard::Scancode::F19;
        case SDL_SCANCODE_F20:
            return sf::Keyboard::Scancode::F20;
        case SDL_SCANCODE_F21:
            return sf::Keyboard::Scancode::F21;
        case SDL_SCANCODE_F22:
            return sf::Keyboard::Scancode::F22;
        case SDL_SCANCODE_F23:
            return sf::Keyboard::Scancode::F23;
        case SDL_SCANCODE_F24:
            return sf::Keyboard::Scancode::F24;

        case SDL_SCANCODE_PRINTSCREEN:
            return sf::Keyboard::Scancode::PrintScreen;
        case SDL_SCANCODE_SCROLLLOCK:
            return sf::Keyboard::Scancode::ScrollLock;
        case SDL_SCANCODE_PAUSE:
            return sf::Keyboard::Scancode::Pause;
        case SDL_SCANCODE_INSERT:
            return sf::Keyboard::Scancode::Insert;
        case SDL_SCANCODE_HOME:
            return sf::Keyboard::Scancode::Home;
        case SDL_SCANCODE_PAGEUP:
            return sf::Keyboard::Scancode::PageUp;
        case SDL_SCANCODE_DELETE:
            return sf::Keyboard::Scancode::Delete;
        case SDL_SCANCODE_END:
            return sf::Keyboard::Scancode::End;
        case SDL_SCANCODE_PAGEDOWN:
            return sf::Keyboard::Scancode::PageDown;
        case SDL_SCANCODE_RIGHT:
            return sf::Keyboard::Scancode::Right;
        case SDL_SCANCODE_LEFT:
            return sf::Keyboard::Scancode::Left;
        case SDL_SCANCODE_DOWN:
            return sf::Keyboard::Scancode::Down;
        case SDL_SCANCODE_UP:
            return sf::Keyboard::Scancode::Up;
        case SDL_SCANCODE_NUMLOCKCLEAR:
            return sf::Keyboard::Scancode::NumLock;
        case SDL_SCANCODE_KP_DIVIDE:
            return sf::Keyboard::Scancode::NumpadDivide;
        case SDL_SCANCODE_KP_MULTIPLY:
            return sf::Keyboard::Scancode::NumpadMultiply;
        case SDL_SCANCODE_KP_MINUS:
            return sf::Keyboard::Scancode::NumpadMinus;
        case SDL_SCANCODE_KP_PLUS:
            return sf::Keyboard::Scancode::NumpadPlus;
        case SDL_SCANCODE_KP_EQUALS:
            return sf::Keyboard::Scancode::NumpadEqual;
        case SDL_SCANCODE_KP_ENTER:
            return sf::Keyboard::Scancode::NumpadEnter;
        case SDL_SCANCODE_KP_PERIOD:
            return sf::Keyboard::Scancode::NumpadDecimal;
        case SDL_SCANCODE_KP_1:
            return sf::Keyboard::Scancode::Numpad1;
        case SDL_SCANCODE_KP_2:
            return sf::Keyboard::Scancode::Numpad2;
        case SDL_SCANCODE_KP_3:
            return sf::Keyboard::Scancode::Numpad3;
        case SDL_SCANCODE_KP_4:
            return sf::Keyboard::Scancode::Numpad4;
        case SDL_SCANCODE_KP_5:
            return sf::Keyboard::Scancode::Numpad5;
        case SDL_SCANCODE_KP_6:
            return sf::Keyboard::Scancode::Numpad6;
        case SDL_SCANCODE_KP_7:
            return sf::Keyboard::Scancode::Numpad7;
        case SDL_SCANCODE_KP_8:
            return sf::Keyboard::Scancode::Numpad8;
        case SDL_SCANCODE_KP_9:
            return sf::Keyboard::Scancode::Numpad9;
        case SDL_SCANCODE_KP_0:
            return sf::Keyboard::Scancode::Numpad0;

        case SDL_SCANCODE_APPLICATION:
            return sf::Keyboard::Scancode::Application;
        case SDL_SCANCODE_EXECUTE:
            return sf::Keyboard::Scancode::Execute;
        case SDL_SCANCODE_MODE:
            return sf::Keyboard::Scancode::ModeChange;
        case SDL_SCANCODE_HELP:
            return sf::Keyboard::Scancode::Help;
        case SDL_SCANCODE_MENU:
            return sf::Keyboard::Scancode::Menu;
        case SDL_SCANCODE_SELECT:
            return sf::Keyboard::Scancode::Select;
        case SDL_SCANCODE_CUT:
            return sf::Keyboard::Scancode::Cut;
        case SDL_SCANCODE_COPY:
            return sf::Keyboard::Scancode::Copy;
        case SDL_SCANCODE_PASTE:
            return sf::Keyboard::Scancode::Paste;
        case SDL_SCANCODE_VOLUMEUP:
            return sf::Keyboard::Scancode::VolumeUp;
        case SDL_SCANCODE_VOLUMEDOWN:
            return sf::Keyboard::Scancode::VolumeDown;
        case SDL_SCANCODE_AUDIOPLAY:
            return sf::Keyboard::Scancode::MediaPlayPause;
        case SDL_SCANCODE_AUDIOSTOP:
            return sf::Keyboard::Scancode::MediaStop;
        case SDL_SCANCODE_AUDIONEXT:
            return sf::Keyboard::Scancode::MediaNextTrack;
        case SDL_SCANCODE_AUDIOPREV:
            return sf::Keyboard::Scancode::MediaPreviousTrack;
        case SDL_SCANCODE_LCTRL:
            return sf::Keyboard::Scancode::LControl;
        case SDL_SCANCODE_LSHIFT:
            return sf::Keyboard::Scancode::LShift;
        case SDL_SCANCODE_LALT:
            return sf::Keyboard::Scancode::LAlt;
        case SDL_SCANCODE_LGUI:
            return sf::Keyboard::Scancode::LSystem;
        case SDL_SCANCODE_RCTRL:
            return sf::Keyboard::Scancode::RControl;
        case SDL_SCANCODE_RSHIFT:
            return sf::Keyboard::Scancode::RShift;
        case SDL_SCANCODE_RALT:
            return sf::Keyboard::Scancode::RAlt;
        case SDL_SCANCODE_RGUI:
            return sf::Keyboard::Scancode::RSystem;
        case SDL_SCANCODE_AC_BACK:
            return sf::Keyboard::Scancode::Back;
        case SDL_SCANCODE_AC_FORWARD:
            return sf::Keyboard::Scancode::Forward;
        case SDL_SCANCODE_AC_REFRESH:
            return sf::Keyboard::Scancode::Refresh;
        case SDL_SCANCODE_AC_STOP:
            return sf::Keyboard::Scancode::Stop;
        case SDL_SCANCODE_AC_SEARCH:
            return sf::Keyboard::Scancode::Search;
        case SDL_SCANCODE_AC_BOOKMARKS:
            return sf::Keyboard::Scancode::Favorites;
        case SDL_SCANCODE_AC_HOME:
            return sf::Keyboard::Scancode::HomePage;
        case SDL_SCANCODE_APP1:
            return sf::Keyboard::Scancode::LaunchApplication1;
        case SDL_SCANCODE_APP2:
            return sf::Keyboard::Scancode::LaunchApplication2;
        case SDL_SCANCODE_MAIL:
            return sf::Keyboard::Scancode::LaunchMail;

        default:
            return sf::Keyboard::Scancode::Unknown;
        }
    }
};